title: "eRačun Hrvatska — Datumi i porezna obveza"
description: "Dokumentacija o datumima i poreznoj obvezi u hrvatskom eRačunu (HR CIUS 2025 / EN16931)"
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
  syntax_highlighter: rouge

url: "https://dageci.github.io"
baseurl: "/eracun-fiskalizacija-datumi"

google_analytics: "G-ZDYRC1DMJZ"  # GA4 Measurement ID za praćenje posjeta
